module.exports = {
    PLAYER_CONNECTED: 'PLAYER_CONNECTED',
    PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
    VERIFY_USERNAME: 'VERIFY_USERNAME',
    LOGOUT: 'LOGOUT',
    INVITATION: 'INVITATION',
    INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
    GAME_STARTED: 'GAME_STARTED',
    GAME_MOVE: 'GAME_MOVE',
    WIN: 'WIN',
    REFRESH_PLAYERS: 'REFRESH_PLAYERS'
}
