module.exports = {
  PLAYER_CONNECTED: 'PLAYER_CONNECTED',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  VERIFY_USERNAME: 'VERIFY_USERNAME',
  LOGOUT: 'LOGOUT',
  INVITATION: 'INVITATION',
  GAME_STARTED: 'GAME_STARTED'
}
