module.exports = {
  PLAYER_CONNECTED: 'PLAYER_CONNECTED',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  VERIFY_USERNAME: 'VERIFY_USERNAME',
  GET_PLAYERLIST: 'GET_PLAYERLIST',
  LOGOUT: 'LOGOUT',
  INVITATION_RECEIVED: 'INVITATION_RECEIVED',
  INVITATION_SENT: 'INVITATION_SENT',
  GAME_STARTED: 'GAME_STARTED'
}
